SELECT * 
FROM RESTAURANTS.RESTAURANTS


SELECT COMPANY_NAME, CITY, STATE 
FROM RESTAURANTS.RESTAURANTS
WHERE STATE like 'PA'


SELECT COMPANY_NAME, CITY, STATE 
FROM RESTAURANTS.RESTAURANTS
WHERE STATE like 'PA'
ORDER BY 2

SELECT ENIGMA_ID, COMPANY_NAME, CITY, STATE 
FROM RESTAURANTS.RESTAURANTS
WHERE STATE like 'CA'
ORDER BY 1 ASC

SELECT AVG(LATEST_PROJECTED_CARD_REVENUE__12M__AVERAGE_MONTHLY_AMOUNT)
FROM RESTAURANTS.RESTAURANTS

SELECT SUM(LATEST_PROJECTED_CARD_REVENUE__12M__AVERAGE_MONTHLY_AMOUNT)
FROM RESTAURANTS.RESTAURANTS


SELECT *
FROM RESTAURANTS.RESTAURANTS
WHERE POSTAL_CODE < 3100


SELECT *
FROM RESTAURANTS.RESTAURANTS
WHERE COMPANY_NAME LIKE '%TREATS'

SELECT *
FROM RESTAURANTS.RESTAURANTS
WHERE CITY LIKE '%ILLE' OR STATE LIKE 'PA'

SELECT *
FROM RESTAURANTS.RESTAURANTS
WHERE STREET_ADDRESS1 LIKE '%AVE' AND STATE NOT LIKE 'PA'

SELECT COUNT(COMPANY_NAME), STATE
FROM RESTAURANTS.RESTAURANTS
GROUP BY STATE
ORDER BY COUNT(STATE) DESC

SELECT COMPANY_NAME, CITY, STATE
FROM RESTAURANTS.RESTAURANTS
WHERE STATE IN ('NY') OR CITY IN ('SAN FRANCISCO')
ORDER BY 3

SELECT ENIGMA_ID, COMPANY_NAME, LATEST_PROJECTED_CARD_REVENUE_GROWTH__3M__RATE_SA
FROM RESTAURANTS.RESTAURANTS
WHERE LATEST_PROJECTED_CARD_REVENUE_GROWTH__3M__RATE_SA BETWEEN .03 AND .05


SELECT TOP 20 COMPANY_NAME, LATEST_PROJECTED_CARD_REVENUE__12M__AVERAGE_MONTHLY_AMOUNT, CITY, STATE
FROM RESTAURANTS.RESTAURANTS
WHERE LATEST_PROJECTED_CARD_REVENUE__12M__AVERAGE_MONTHLY_AMOUNT > 150000
ORDER BY 2 DESC


SELECT TOP 5 COMPANY_NAME, CITY, STATE, LATEST_PROJECTED_CARD_REVENUE__12M__AVERAGE_MONTHLY_AMOUNT, LATEST_PROJECTED_CARD_REVENUE_GROWTH__3M__RATE_SA
FROM RESTAURANTS.RESTAURANTS
WHERE LATEST_PROJECTED_CARD_REVENUE__12M__AVERAGE_MONTHLY_AMOUNT < 10000 AND LATEST_PROJECTED_CARD_REVENUE_GROWTH__3M__RATE_SA <.0
ORDER BY 4 DESC








